### ISSUE TITLE
How to handle synchronizing the gameplay state with the ui state?

### ISSUE THREAD

**Issue by agathazeren** [asa-z/cuneiforbits#12]
The big question here is whether to have an `Update` type that encodes all possible gameplay changes, or to just have the ui update. There is also the question of, if we don't have a formal `Update`, then which part of the code is responsible for updating the ui.

**Comment by yvnat** [comment]
`Update` sounds very good for making nice, neat code, but it will make adding new features much more cumbersome. I suggest making do without it **for now** for the sake of completing the prototype version of the game, and then refactoring the code at a later point to include `Update`.

**Comment by agathazeren** [comment]
That seems like a reasonable course of action. We will see how bad the code ends up being.
