### ISSUE TITLE
Pick a TUI library

### ISSUE THREAD

**Issue by agathazeren** [asa-z/cuneiforbits#2]
Our options are: 
 - [tui-rs](docs.rs/tui)
 - [cursive](docs.rs/cursive)
 - Roll our own system (using a terminal backend, not raw escapes)

[Comparison by cursive](https://github.com/gyscos/cursive/wiki/Cursive-vs-tui%E2%80%90rs)

**Comment by yvnat** [comment]
As I envision it, the interface should be simple enough that there is no reason to use an external library to do formatting and such, though something will probably be necessary for user input.
One problem that I don't think any of the libraries can solve is the fact that the windows console (I can't speak for any other operating systems) will be unable to render the cuneiforms without a very specialized font that we will need to make.

**Comment by agathazeren** [comment]
Windows is always a problem. If we roll our own, we would still probably use a library such as [termion](docs.rs/termion) in so we don't have to deal with escapes on our own. But that is also the direction I was leaning. I will do some research as to what libraries would be good for this.

**Comment by agathazeren** [comment]
I have conducted a brief review of the ecosystem, and I am thinking that we should use [termion](lib.rs/termion). The one downside of this is that it would not support windows by default (though I think it would be possible to put middleware before stdout to support windows at a small overhead in the future). If we need to support windows, the I'm thinking either [crossterm](lib.rs/crossterm) or [terminal](lib.rs/terminal), however, I much prefer the api of termion. What are your thoughts?

**Comment by yvnat** [comment]
Adding windows support will probably be impossible through the terminal anyways due to font limitations- It would need to be done through some sort of graphical emulator. Because of this, I see no reason not to use termion.
