### ISSUE TITLE
Should we have a `Game` struct.

### ISSUE THREAD

**Issue by agathazeren** [asa-z/cuneiforbits#7]
Should we have a master Game struct? or should we use global state? An in between would be a Game struct we have in global state. 

Reasons for a struct
 - Cleaner?
 - Easier to expand the code and encapsulate the game
 - Maybe some things are easier, such as save games, or multiplayers

Reasons for global state
 - No need to mess with dependency injecting everywhere
 - Maybe this will end up being cleaner?
 - Perhaps will end up with less complexity. 

I am currently thinking that we should go for option C, that is, make a Game struct and then hold a copy in a static. (However, then the game struct must have synchronizations inside it, which is probably not bad.

**Comment by yvnat** [comment]
I don't think this really matters until the game gets very big- much larger than it is likely to ever become. If you prefer option C, then that is what we should do.

**Comment by agathazeren** [comment]
Sounds reasonable.
