### ISSUE TITLE
How to determine cuneiform width

### ISSUE THREAD

**Issue by agathazeren** [asa-z/cuneiforbits#9]
[`unicode_width`](lib.rs/unicode_width) does not support getting the proper display width of cuneiform characters. I have searched for some code that does this, but cannot find any, nor does it seem that there is any standardization on this. I think that the only option would be to create our own library to do this.

**Comment by yvnat** [comment]
The width of the cuneiforms is strictly a display problem, and by good practice should be dealt with only by the struct responsible for display. That said, there also needs to be awareness of character width in the UI.

I suggest having the display deal with single-width characters (with wider characters obscuring the characters after them), and having the UI struct handle cuneiform width by means of a dictionary containing the approximate width of every cuneiform. That way, only dictionary of cuneiform widths needs to be maintained.

**Comment by agathazeren** [comment]
Yes, it would just be a dictionary (probably using a binary search). However, since this functionality is so orthogonal, I would factor it out into a separate crate. I think I'm going to do that.

**Comment by agathazeren** [comment]
I have successfully implemented this functionality in another crate: [github.com/asa-z/cuneiform_widths]
